### ISSUE TITLE
Apply UltraFace-RFB-640 model

### ISSUE THREAD

**Issue by livingbeams** [keijiro/UltraFaceBarracuda#1]
Hi Keijiro,

Congratulations on your great work once more.

I have been trying to adapt the code in this repository to apply the UltraFace-RFB-640 model instead of the UltraFace-RFB-320 model.

The only problem I find is when applying the first post-processing step through RenderTextures.

While for the 320x240 input network the maxdetections size is 4420, for the 640x480 input network the maxdetections size is 17640 (curiously it is not 4420 x 4 = 17680).

The problem I am facing is that is not possible to allocate a RenderTexture of 2x17680 or 4x17680.

I think it could be possible to reshape the output tensors "scores" and "boxes" to a more "square" format:
barracudaWorker.PeekOutput("scores").Reshape(new TensorShape(1, maxDetection / 4, 2 * 4, 1))
barracudaWorker.PeekOutput("boxes").Reshape(new TensorShape(1, maxDetection / 4, 4 * 4, 1))

But then I am a bit lost about how the ComputeShader should use the SV_DispatchThreadID to parse the BoundingBoxes data.

Do you think allocating more "square" RenderTextures is the best option or do you think it is possible to extract the output tensor data some other way?

Best regards.

**Comment by keijiro** [comment]
> Do you think allocating more "square" RenderTextures is the best option or do you think it is possible to extract the output tensor data some other way?

Yes. I'm sure that that's the only option to solve the issue.

**Comment by livingbeams** [comment]
All right. Thank you for your answer.

**Comment by keijiro** [comment]
Added UltraFace-RFB-640 support in the recent commits.
